version: '3'

services:
  fila:
    image: rabbitmq:management
  producer:
    image: celsocrivelaro/python3-pika
    volumes:
      - .:/app
    links:
      - fila
      - mongo
      - mongo-express
  consumer:
    image: celsocrivelaro/python3-pika
    volumes:
      - .:/app
    links:
      - fila
      - mongo
      - mongo-express
    depends_on:
      - fila
    command: ["./wait-for-it.sh", "fila:5672", "--", "python", "-u", "consumer.py"]

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: martevi
      ME_CONFIG_BASICAUTH_PASSWORD: senac2019
      ME_CONFIG_MONGODB_PORT: 27017
    links:
      - mongo
    networks: 
      - ep02net
  
  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - .:/app/data/mongodb
    networks:
     - ep02net
    
networks: 
  ep02net:
    driver: bridge
  